name: ffhq256-sr
prior: checkpoints/ffhq256.pt
model:
  _target_: inverse_problems.image_restore.SuperResolution
  sigma_noise: 0.05
  scale_factor: 2
  in_resolution: 256

data:
  _target_: training.dataset.ImageFolder
  root: ../data/ffhq256
  resolution: 256
  num_channels: 3
  id_list: 0-9

evaluator:
  _target_: eval.Image

exp_dir: exps/inference/ffhq256-sr