name: navier-stokes
prior: checkpoints/ns-5m.pt
model:
  _target_: inverse_problems.navier_stokes.ForwardNavierStokes2d
  forward_time: 1.0
  Re: 200.0
  resolution: 128
  downsample_factor: 2
  sigma_noise: 0.0
  unnorm_scale: 10.0

data:
  _target_: training.dataset.LMDBData
  root: ../data/navier-stokes-val/Re200.0-t5.0
  resolution: 128
  std: 5.0
  id_list: 0-4

evaluator:
  _target_: eval.NavierStokes2d

exp_dir: exps/inference/navier-stokes
